export const GET_CONFIRM_OK_RESERVATION = 'GET_CONFIRM_OK_RESERVATION';
export const SYNC_RESERVATIONS = 'SYNC_RESERVATIONS';
export const SYNC_RESERVATIONS_REQUEST = 'SYNC_RESERVATIONS_REQUEST';
export const SYNC_RESERVATIONS_ERROR = 'SYNC_RESERVATIONS_ERROR';
