export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const RELOGIN_SUCCESS = 'RELOGIN_SUCCESS'
export const LOGIN_PROVIDER_FIRST_TIME = 'LOGIN_PROVIDER_FIRST_TIME'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CHANGE_USER_TO_SUPPLIER = 'CHANGE_USER_TO_SUPPLIER'
export const LOGIN_PROVIDER_STAY_USER = 'LOGIN_PROVIDER_STAY_USER'
