export const LIST_EQUIPMENTS = 'LIST_EQUIPMENT';
export const LIST_LOAN = 'LIST_LOAN';
export const LIST_WAITING = 'LIST_WAITING';
export const LIST_BOOKED = 'LIST_BOOKED';
export const DISPLAY_LIST_EQUIPMENTS = 'LIST_ALL_EQUIPMENTS';
export const LIST_EQUIPMENTS_FOR_FOURNISSEUR = 'LIST_EQUIPMENTS_FOR_FOURNISSEUR';
export const LIST_LOAN_FOURNISSEUR = 'LIST_LOAN_FOURNISSEUR';
export const DISPLAY_RETURN_EQUIPMENTS = 'DISPLAY_RETURN_EQUIPMENTS';
export const LIST_OVERDUE = 'LIST_OVERDUE';

