export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const ONE_CATEGORIES = 'ONE_CATEGORIES';
export const LIST_CATEGORIES_FOR_FOURNISSEUR = 'LIST_CATEGORIES_FOR_FOURNISSEUR';
