export const GET_ONE_EQUIPMENT = 'GET_ONE_EQUIPMENT';
export const GET_LIST_CATEGORIES = 'GET_LIST_CATEGORIES';
export const GOT_EQUIPMENT_OWNER = 'GOT_EQUIPMENT_OWNER';
export const GET_ONE_EQUIPMENT_FOR_EDIT = 'GET_ONE_EQUIPMENT_FOR_EDIT';
export const GET_LIST_CATEGORIES_FOR_EDIT = 'GET_LIST_CATEGORIES_FOR_EDIT';

