export const PASSWORD_CHANGE_IN_PROGRESS = 'PASSWORD_CHANGE_IN_PROGRESS'
export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR'
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS'

